package com.example.data.io

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.example.data.model.LedgerBook
import com.example.data.model.TransactionRecord
import com.example.data.model.TransactionType
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfReportGenerator {

    private val reportGenDateFormat = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.US)
    private val tableDateFormat = SimpleDateFormat("dd MMM yy", Locale.US)
    private val monthFormat = SimpleDateFormat("MMMM yyyy", Locale.US)
    private val durationDateFormat = SimpleDateFormat("dd MMM yyyy", Locale.US)

    fun generateFinancialStatement(
        context: Context,
        book: LedgerBook,
        transactions: List<TransactionRecord>,
        timeframeLabel: String = "All Time"
    ): File {
        val pdfDocument = PdfDocument()
        val pageWidth = 595 // Standard A4 width in points
        val pageHeight = 842 // Standard A4 height in points
        val marginX = 36f
        val contentWidth = pageWidth - (marginX * 2) // 523f

        val sortedTxs = transactions.sortedBy { it.timestamp }

        // Calculate totals
        val totalIncome = sortedTxs.filter { it.type == TransactionType.CASH_IN }.sumOf { it.amount }
        val totalExpense = sortedTxs.filter { it.type == TransactionType.CASH_OUT }.sumOf { it.amount }
        val finalBalance = totalIncome - totalExpense

        // Determine Month & Duration
        val latestTimestamp = if (sortedTxs.isNotEmpty()) sortedTxs.last().timestamp else System.currentTimeMillis()
        val earliestTimestamp = if (sortedTxs.isNotEmpty()) sortedTxs.first().timestamp else System.currentTimeMillis()
        val monthStr = monthFormat.format(Date(latestTimestamp))
        val durationStr = "Duration: ${durationDateFormat.format(Date(earliestTimestamp))} - ${durationDateFormat.format(Date(latestTimestamp))}"

        // Report titles matching user reference
        val reportTitle = if (book.name.contains("Arik", ignoreCase = true) || book.name.equals("Personal", ignoreCase = true)) {
            "Arik Daily Cash Flow Report"
        } else {
            "${book.name} Daily Cash Flow Report"
        }
        val generatedByStr = "Generated On - ${reportGenDateFormat.format(Date())}. Generated by - Arik Md Isthiaque (+8801521493029)"

        // Paints
        val paint = Paint(Paint.ANTI_ALIAS_FLAG)

        var currentPageNum = 1
        var pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, currentPageNum).create()
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas

        var yPos = 36f

        // 1. Header Profile Banner
        val avatarSize = 38f
        val avatarRect = RectF(marginX, yPos, marginX + avatarSize, yPos + avatarSize)
        paint.color = Color.parseColor("#4338CA") // Deep Indigo avatar
        canvas.drawRoundRect(avatarRect, 8f, 8f, paint)

        // Avatar Initials
        paint.color = Color.WHITE
        paint.textSize = 15f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textAlign = Paint.Align.CENTER
        canvas.drawText("CB", marginX + (avatarSize / 2f), yPos + 24f, paint)
        paint.textAlign = Paint.Align.LEFT

        // Title and Subtitle
        paint.color = Color.parseColor("#0F172A")
        paint.textSize = 15f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText(reportTitle, marginX + avatarSize + 12f, yPos + 16f, paint)

        paint.color = Color.parseColor("#64748B")
        paint.textSize = 8.5f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText(generatedByStr, marginX + avatarSize + 12f, yPos + 32f, paint)

        yPos += 54f

        // 2. Month Title
        paint.color = Color.parseColor("#0F172A")
        paint.textSize = 13.5f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText(monthStr, marginX, yPos + 12f, paint)

        yPos += 24f

        // 3. Duration Box
        val durationBoxRect = RectF(marginX, yPos, marginX + contentWidth, yPos + 28f)
        paint.color = Color.WHITE
        paint.style = Paint.Style.FILL
        canvas.drawRect(durationBoxRect, paint)
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 0.8f
        paint.color = Color.parseColor("#E2E8F0")
        canvas.drawRect(durationBoxRect, paint)
        paint.style = Paint.Style.FILL

        paint.color = Color.parseColor("#1E293B")
        paint.textSize = 9.5f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText(durationStr, marginX + 12f, yPos + 18f, paint)

        yPos += 40f

        // 4. Summary 3 Metrics Card Box
        val summaryBoxRect = RectF(marginX, yPos, marginX + contentWidth, yPos + 54f)
        paint.color = Color.WHITE
        paint.style = Paint.Style.FILL
        canvas.drawRect(summaryBoxRect, paint)
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 0.8f
        paint.color = Color.parseColor("#E2E8F0")
        canvas.drawRect(summaryBoxRect, paint)
        paint.style = Paint.Style.FILL

        val colCardWidth = contentWidth / 3f

        // Vertical divider lines in summary box
        paint.color = Color.parseColor("#E2E8F0")
        canvas.drawLine(marginX + colCardWidth, yPos, marginX + colCardWidth, yPos + 54f, paint)
        canvas.drawLine(marginX + colCardWidth * 2, yPos, marginX + colCardWidth * 2, yPos + 54f, paint)

        // Total Cash in
        paint.color = Color.parseColor("#64748B")
        paint.textSize = 8.5f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("Total Cash in", marginX + 12f, yPos + 18f, paint)
        paint.color = Color.parseColor("#10B981") // Green
        paint.textSize = 13f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText(formatAmountWithCommas(totalIncome), marginX + 12f, yPos + 38f, paint)

        // Total Cash out
        paint.color = Color.parseColor("#64748B")
        paint.textSize = 8.5f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("Total Cash out", marginX + colCardWidth + 12f, yPos + 18f, paint)
        paint.color = Color.parseColor("#EF4444") // Red
        paint.textSize = 13f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText(formatAmountWithCommas(totalExpense), marginX + colCardWidth + 12f, yPos + 38f, paint)

        // Final Balance
        paint.color = Color.parseColor("#64748B")
        paint.textSize = 8.5f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("Final Balance", marginX + (colCardWidth * 2) + 12f, yPos + 18f, paint)
        paint.color = Color.parseColor("#0F172A") // Dark
        paint.textSize = 13f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText(formatAmountWithCommas(finalBalance), marginX + (colCardWidth * 2) + 12f, yPos + 38f, paint)

        yPos += 72f

        // 5. Total No. of entries
        paint.color = Color.parseColor("#0F172A")
        paint.textSize = 10f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Total No. of entries: ${sortedTxs.size}", marginX, yPos, paint)

        yPos += 14f

        // Column widths matching reference
        val colDateW = 54f
        val colRemarkW = 126f
        val colCatW = 94f
        val colModeW = 52f
        val colInW = 63f
        val colOutW = 63f
        val colBalW = 71f // Total = 523f

        val colDateX = marginX
        val colRemarkX = colDateX + colDateW
        val colCatX = colRemarkX + colRemarkW
        val colModeX = colCatX + colCatW
        val colInX = colModeX + colModeW
        val colOutX = colInX + colInW
        val colBalX = colOutX + colOutW

        val colPositions = listOf(colDateX, colRemarkX, colCatX, colModeX, colInX, colOutX, colBalX, marginX + contentWidth)

        // Helper to draw table header row
        fun drawTableHeader(c: Canvas, y: Float) {
            val hRect = RectF(marginX, y, marginX + contentWidth, y + 22f)
            paint.color = Color.parseColor("#F8FAFC")
            paint.style = Paint.Style.FILL
            c.drawRect(hRect, paint)

            paint.color = Color.parseColor("#CBD5E1")
            paint.style = Paint.Style.STROKE
            paint.strokeWidth = 0.8f
            c.drawRect(hRect, paint)

            // Vertical divider lines
            for (i in 1 until colPositions.size - 1) {
                c.drawLine(colPositions[i], y, colPositions[i], y + 22f, paint)
            }

            paint.style = Paint.Style.FILL
            paint.color = Color.parseColor("#0F172A")
            paint.textSize = 8.5f
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)

            c.drawText("Date", colDateX + 6f, y + 14f, paint)
            c.drawText("Remark", colRemarkX + 6f, y + 14f, paint)
            c.drawText("Category", colCatX + 6f, y + 14f, paint)
            c.drawText("Mode", colModeX + 6f, y + 14f, paint)
            c.drawText("Cash in", colInX + 6f, y + 14f, paint)
            c.drawText("Cash out", colOutX + 6f, y + 14f, paint)
            c.drawText("Balance", colBalX + 6f, y + 14f, paint)
        }

        // Draw header on Page 1
        drawTableHeader(canvas, yPos)
        yPos += 22f

        val rowHeight = 20f
        var runningBal = 0.0

        for (index in sortedTxs.indices) {
            val tx = sortedTxs[index]
            if (tx.type == TransactionType.CASH_IN) {
                runningBal += tx.amount
            } else {
                runningBal -= tx.amount
            }

            // Check if row exceeds page
            if (yPos + rowHeight > pageHeight - 50f) {
                // Close current page border
                paint.color = Color.parseColor("#CBD5E1")
                canvas.drawLine(marginX, yPos, marginX + contentWidth, yPos, paint)

                drawFooter(canvas, marginX, pageHeight.toFloat())
                pdfDocument.finishPage(page)

                currentPageNum++
                pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, currentPageNum).create()
                page = pdfDocument.startPage(pageInfo)
                canvas = page.canvas
                yPos = 36f

                // Redraw table header on new page
                drawTableHeader(canvas, yPos)
                yPos += 22f
            }

            // Row background
            val rowRect = RectF(marginX, yPos, marginX + contentWidth, yPos + rowHeight)
            paint.style = Paint.Style.FILL
            paint.color = Color.WHITE
            canvas.drawRect(rowRect, paint)

            // Cell borders
            paint.style = Paint.Style.STROKE
            paint.strokeWidth = 0.6f
            paint.color = Color.parseColor("#E2E8F0")
            canvas.drawRect(rowRect, paint)

            for (i in 1 until colPositions.size - 1) {
                canvas.drawLine(colPositions[i], yPos, colPositions[i], yPos + rowHeight, paint)
            }

            paint.style = Paint.Style.FILL
            paint.textSize = 8f
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)

            // Date
            paint.color = Color.parseColor("#1E293B")
            val dateText = tableDateFormat.format(Date(tx.timestamp))
            canvas.drawText(dateText, colDateX + 6f, yPos + 13.5f, paint)

            // Remark
            val remark = tx.memo.ifBlank { tx.category }
            val truncatedRemark = if (remark.length > 24) remark.take(22) + "…" else remark
            canvas.drawText(truncatedRemark, colRemarkX + 6f, yPos + 13.5f, paint)

            // Category
            val cat = tx.category
            val truncatedCat = if (cat.length > 18) cat.take(16) + "…" else cat
            canvas.drawText(truncatedCat, colCatX + 6f, yPos + 13.5f, paint)

            // Mode
            val mode = tx.paymentMode.ifBlank { "Cash" }
            canvas.drawText(mode, colModeX + 6f, yPos + 13.5f, paint)

            // Cash In
            if (tx.type == TransactionType.CASH_IN) {
                paint.color = Color.parseColor("#10B981") // Green
                canvas.drawText(formatAmountWithCommas(tx.amount), colInX + 6f, yPos + 13.5f, paint)
            }

            // Cash Out
            if (tx.type == TransactionType.CASH_OUT) {
                paint.color = Color.parseColor("#EF4444") // Red
                canvas.drawText(formatAmountWithCommas(tx.amount), colOutX + 6f, yPos + 13.5f, paint)
            }

            // Balance
            paint.color = Color.parseColor("#0F172A")
            canvas.drawText(formatAmountWithCommas(runningBal), colBalX + 6f, yPos + 13.5f, paint)

            yPos += rowHeight
        }

        // Final Balance row at end of entries
        if (yPos + rowHeight > pageHeight - 50f) {
            paint.color = Color.parseColor("#CBD5E1")
            canvas.drawLine(marginX, yPos, marginX + contentWidth, yPos, paint)
            drawFooter(canvas, marginX, pageHeight.toFloat())
            pdfDocument.finishPage(page)

            currentPageNum++
            pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, currentPageNum).create()
            page = pdfDocument.startPage(pageInfo)
            canvas = page.canvas
            yPos = 36f

            drawTableHeader(canvas, yPos)
            yPos += 22f
        }

        // Draw Final Balance row
        val finalRowRect = RectF(marginX, yPos, marginX + contentWidth, yPos + rowHeight)
        paint.style = Paint.Style.FILL
        paint.color = Color.WHITE
        canvas.drawRect(finalRowRect, paint)

        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 0.8f
        paint.color = Color.parseColor("#CBD5E1")
        canvas.drawRect(finalRowRect, paint)

        for (i in 1 until colPositions.size - 1) {
            canvas.drawLine(colPositions[i], yPos, colPositions[i], yPos + rowHeight, paint)
        }

        paint.style = Paint.Style.FILL
        val lastDateStr = if (sortedTxs.isNotEmpty()) tableDateFormat.format(Date(sortedTxs.last().timestamp)) else ""
        paint.color = Color.parseColor("#1E293B")
        paint.textSize = 8f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText(lastDateStr, colDateX + 6f, yPos + 13.5f, paint)

        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Final Balance", colRemarkX + 6f, yPos + 13.5f, paint)
        canvas.drawText(formatAmountWithCommas(runningBal), colBalX + 6f, yPos + 13.5f, paint)

        yPos += rowHeight + 10f

        // Draw footer on last page
        drawFooter(canvas, marginX, pageHeight.toFloat())
        pdfDocument.finishPage(page)

        // Save to cache exports folder
        val exportDir = File(context.cacheDir, "exports").apply { mkdirs() }
        val sanitizedName = book.name.replace("[^a-zA-Z0-9]".toRegex(), "_")
        val file = File(exportDir, "${sanitizedName}_Cash_Flow_Report_${System.currentTimeMillis()}.pdf")
        val fos = FileOutputStream(file)
        pdfDocument.writeTo(fos)
        fos.flush()
        fos.close()
        pdfDocument.close()

        return file
    }

    private fun formatAmountWithCommas(amount: Double): String {
        return if (amount % 1.0 == 0.0) {
            String.format(Locale.US, "%,.0f", amount)
        } else {
            String.format(Locale.US, "%,.2f", amount)
        }
    }

    private fun drawFooter(canvas: Canvas, marginX: Float, pageHeight: Float) {
        val paint = Paint(Paint.ANTI_ALIAS_FLAG)
        val y = pageHeight - 32f

        // Small blue icon box
        val iconRect = RectF(marginX, y - 10f, marginX + 16f, y + 6f)
        paint.color = Color.parseColor("#2563EB")
        canvas.drawRoundRect(iconRect, 4f, 4f, paint)

        paint.color = Color.WHITE
        paint.textSize = 10f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("C", marginX + 4f, y + 2.5f, paint)

        paint.color = Color.parseColor("#475569")
        paint.textSize = 8.5f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("Generated by CashBook App.", marginX + 22f, y + 2.5f, paint)
    }
}
